### ISSUE TITLE
Summary box for combined retirement does not update

### ISSUE THREAD

**Issue by matthewjheaney** [Gregable/social-security-tools#120]
In the section "Early and Delayed Combined Retirement", you can hover over the plot to get a vertical dotted line indicating the month, and a summary box which computes the total benefit for self and spouse.

If I drag the vertical line indicator and click, I can fix the line on a specific location on the graph.  When the vertical line is present, I also get a summary box underneath the graph, that gives the total amount for self and spouse.

The "I plan to work for" slider is visible when you navigate to this part of the page (thanks for that -- very helpful for running what-if scenarios).  If you adjust that slider to change the number of more years you plan to work, the self value adjacent to the self terminal benefit amount (the bit in orange) does update, correctly.

However, if you drag the "I plan to work for slider" the information in the summary box (associated with the position of the vertical line) does not also get updated (only the info on the plot itself).  The info in the summary box remains fixed at the values that were true when you dragged-and-clicked the vertical slider to leave it fixed on the graph.  But the info in the box does not update if you then go to the top of the viewport and manipulate the "I plan to work for slider".

**Comment by Gregable** [comment]
Thanks for the report, this isn't one I had noticed. Should be easy to fix next time I have a few minutes.
