### ISSUE TITLE
Allow user to ignore credits calculation

### ISSUE THREAD

**Issue by Gregable** [Gregable/social-security-tools#176]
For a user with fewer than 40 credits, the tool doesn't allow them to continue unless they enter future years of earnings. There are some corner cases, such as [Canadian Work Credits](https://www.ssa.gov/international/Agreement_Pamphlets/documents/Canada.pdf) where the 40 credit calculation may be wrong or irrelevant. 

At the very least, it would be good to give the user an option to click through a warning and generate benefit estimates anyway. In this way if the user knew they had an exception or just wanted to see how the tool works, that option would be available.

**Comment by robinlavallee** [comment]
It is actually a linear formula. As an example case, if I have 24 credits for US SSA and thus will need 16 credits from Canada to be eligible. Hence, the computation is 24/(24+16) = 60%. I will get 60% of the expected benefits from US SSA.

The exact wording of the treaty is:
"Where entitlement to a benefit under United States laws is established according to the provisions of paragraph (1) of this Article, a pro rata primary insurance amount shall be computed based on the ratio of the total periods of coverage completed under United States laws to the total periods of coverage completed under the laws of the two Contracting States. Benefits payable under United States laws on the basis of an earnings record where a pro rata primary insurance amount has been computed shall be paid on the basis of that pro rata primary insurance amount."
Source: https://www.treaty-accord.gc.ca/text-texte.aspx?lang=eng&id=102189

**Comment by Gregable** [comment]
This is a list of possible peering agreements: https://www.ssa.gov/international/agreements_overview.html

It would be good to provide links to all of this as a follow up.
