### ISSUE TITLE
Online tool not working 

### ISSUE THREAD

**Issue by skylr1** [Gregable/social-security-tools#202]
Your online tool at https://ssa.tools/calculator.html does not work.
The act of pasting the data into the input box does not do anything.
There is no button to trigger any action either.
The only buttons on that page are 3 "Try the Demo" buttons which will only shows demo data calculations.
I would expect the tool to act when I paste the data into the input box or some sort of "Submit" or "Calculate" button on that page to trigger calculations but there are none.
It looks like you have some javascript errors (ReferenceError: MAX_YEAR is not defined)

**Comment by Gregable** [comment]
It's supposed to automatically advance when you paste valid input. I can't reproduce the MAX_YEAR. I wonder if for some reason your browser was unable to load one of the supporting javascript files. 

Please give it another try. Take a look at the network tab of your devtools to see if there were any network errors involved.

**Comment by skylr1** [comment]
I see the problem now.  My data have future years (e.g. 2023, 2024, 2025, 2026, ... etc).  The tool doesn't give an error nor respond in any way.  I can see an error only when I check the console output.  A suggestion is to return a warning message notifying users to not paste data beyond current year rather than failed silently.

**Comment by Gregable** [comment]
Did the ssa.gov site give you data from future years when copy/pasting? If so, do you know why it did so in your case - I've never heard of that happening before, but I don't have a lot of data points.
