### ISSUE TITLE
Does ssa.tools support passing form data via query string or similar?

### ISSUE THREAD

**Issue by rrelyea** [Gregable/social-security-tools#213]
Would like to explore having site at https://bogle.tools/portfolio able to launch sites like ssa.tools passing the data that may have already been entered.

**Comment by Gregable** [comment]
Not currently, but I'm open to implementing if we can decide what inputs would be useful.

Generally the site has two inputs from the user.

1. [Copy / paste dump](https://ssa.tools/static/copy-paste-demo.mp4) from ssa.gov of user's earnings history.
2. Birthdate

Implementing a data pass-thru if you have these two values would be straightforward, but I'm worried that the ssa.gov paste may be a confusing user experience for the user on your site.

The former could be replaced with the user's estimated PIA, a single value, if the user were to know it. In that case, the first few sections of the site that show how PIA is computed would not be shown. However, unless the user is already at retirement age, it's somewhat tricky for them to compute estimate PIA from the social security site.

Another way we could imagine doing this, would be the reverse direction. If the user doesn't know their PIA, you could navigate them to a special URL on ssa.tools which prompts for the above inputs and at the end of the flow provides a link back to bogle.tools with the user's PIA.

Various options to consider, let me know what you have in mind.

**Comment by Gregable** [comment]
@rrelyea Do you have specific inputs you'd like to pass in? Let me know what you have in mind.

**Comment by Gregable** [comment]
Implemented PIA-based input here: https://github.com/Gregable/social-security-tools/pull/282

URL string looks like:

```
/calculator#pia1=3000&dob1=1965-09-21&name1=Alex
/calculator#pia1=3000&dob1=1965-09-21&name1=Alex&pia2=500&dob2=1962-09-28&name2=Chris
```

Date of birth is `YYYY-MM-DD`
