### ISSUE TITLE
Bend points and index factors might be incorrect?

### ISSUE THREAD

**Issue by stkeros** [Gregable/social-security-tools#22]
Using your demo example of a person born in 1950 with the 5 earnings years. The bend points should be from 2012 (age 60, see here https://www.ssa.gov/oact/cola/bendpoints.html). I think perhaps you are using the bendpoints from 2017?

Also, I get different index factors that you, I suspect due to the same error which is causing the wrong bendpoints. Since my index is different, so is the PIA.

For the 5 years of earnings, I believe the correct index factors range from 3.33...2.58 for years 1980 to 1984. But I don't know if those are based on the most recent wage index  (2015).

I don't know anything about java, so don't know how to evaluate for formulas to help with the source of the error.

**Comment by Gregable** [comment]
OK, I think I understand what I've done wrong here. The benefit computation is essentially 'frozen' at the time that the participant reaches 62. This includes the bend points and index factors. These values do not keep changing after that point.

So it's insufficient to know the index factors and bend points in 2017, the tool needs to also know them for earlier years.

This means that the tool produces correct results for folks who turn 62 in 2017 or later, but not for folks who turn 62 in years before 2017. It overestimates their benefit.

I'll work on this.

**Comment by stkeros** [comment]
Exactly. Benefits need to be known by age 62 in order for a person to claim them. Benefits depend on the average wage index. There is a 1.5 year delay before that data is released, thus age 60 is used as the index year, set at 1.0, and for every year thereafter. That has the effect of making earnings from 60 onwards somewhat more valuable than earnings in before age 60.

So the bend points become:

1st: (Age 60 NAWI) / (1977 NAWI) times 180
2nd: same ratio of age 60 NAWI to 1977 NAWI as above, but times 1085

The net effect is that until age 60, the benefit or PIA is only affected by earnings and wage growth. From age 60 onward, the benefit is only affected by additional earnings (if any) and CPI changes.

If both wage growth and CPI are assumed to be zero, then the tool can just set the current year as the "index year" (because all future years will have the same index of 1.0) and thus the bend points used will be today's bend points.

**Comment by Gregable** [comment]
@stkeros When you have some time, please take another look to see if the bendpoints and index factors look correct now. I had some time over the weekend to work on them.

You may need to hard refresh the resources in your browser. The easiest way to do that is to use the key combo Control+Shift+R.

**Comment by stkeros** [comment]
I entered one set of earnings history (my own) and it seems the bend points and benefit amount are correct. You are off by a small amount ($3-$5 here and there), likely because you did not apply certain rounding rules which happen along the way. One example,, the PIA is rounded down to the nearest dime. But I'm not sure anyone needs this tool to be that exact.

When I entered my earnings, it did not ask for my age. Will the calculator work if one is over 60 years old? Bendpoint are fixed in the year one turns 60. So a 65 year old is no going to have the same bendpoints as a 62 year old or a 50 year old.

But otherwise, it seem as if the tool works as you intend!

**Comment by Gregable** [comment]
Thank you for spot checking it. Yes, it's a few dollars off for me as well. I'd like to get the numbers to exactly match the ssa.gov site ideally, since it lends a little more credibility to the calculations, though I'm unsure where all of the rounding is happening. Do you know of any reference documents?

Regarding asking for your age, the tool asks for your birth day/month when computing your normal retirement age, a little further down. If you specify an age >60, it'll update the calculations at the top of the document and show an alert text notifying the user that the PIA calculation was updated.

I might ask for age a little earlier in the flow due to this, so as to reduce confusion. Good point to raise.

**Comment by stkeros** [comment]
don't have references but this is what I know from memory:

bend points get rounded to nearest integer.
AIME gets rounded down to the nearest dollar
PIA gets rounded down to nearest dime
Monthly benefit gets rounded down to the nearest dollar.

There are a few other places where you might not be able to get it exactly. SSA uses FRACTIONS in their internal calculations, and not decimals. I don't remember where. Probably the last thing you should worry about.

**Comment by Gregable** [comment]
OK, rounding should be a little better now. I switched PIA computation to monthly so that it's a little clearer what rounding is happening if someone checks the math displayed.
