### ISSUE TITLE
Number of decimal places used to calculate indexed earnings is incorrect

### ISSUE THREAD

**Issue by stkeros** [Gregable/social-security-tools#31]
Using your example of the worker born in 1950 with 5 years of earnings, I get a different sum for the index earnings. I get 464,295 while you get 464,293. 

I think this is because you aren't using enough decimal places. Below is a link which explains the procedure used calculated indexed earnings. 

In your case, I see that your "multiplier" (officially known as the index factor) only displays 2 decimals. But the calculation should use an index factor to at least 7 decimals in order to be consistent with SSA calculations. Then, after multiplying the earnings times the index factor, you round the earnings down to the nearest penny.

In this particular example, although the sum of the earnings changes by $2 after fixing the error, the PIA does not change, due to other rounding done later.

https://secure.ssa.gov/poms.nsf/lnx/0300605018

C. Procedure

To index earnings:
Multiply the posted earnings up to the maximum creditable for each year after 1950 up to the indexing year by the average wages of all workers for the indexing year; and
Divide the result by the average earnings of all workers for the year being indexed. Carry to three decimal places and round to the nearest cent; i.e., if third decimal place is 4 or less, round down; if 5 or more, round up.

**Comment by Gregable** [comment]
I'll look into this one.  I don't think I'm rounding at all here internally. I'm only rounding the displayed number. It's also possible that I'm using too many decimal places and should be rounding more. Thanks for the tests!

**Comment by Gregable** [comment]
I was computing the indexing factors with lots of precision, but was rounding the annual indexed wage to the dollar. It should be better now.
