### ISSUE TITLE
AnyPIA output format not recognized by site

### ISSUE THREAD

**Issue by Gregable** [Gregable/social-security-tools#45]
A user has reported that it would be nice if the output format from the AnyPIA tool could be used in the site as well. Seems like a good idea to support.

An example of the format was provided as:

```
Amount Quarters
Annual Maximum per of
year earnings earnings QC coverage
1975 8,557.00 14,100.00
1976 10,118.00 15,300.00
1977 12,845.00 16,500.00
1978 13,444.00 17,700.00 250.00 4
1979 14,898.00 22,900.00 260.00 4
1980 6,447.00 25,900.00 290.00 4
```

**Comment by stkeros** [comment]
What about an input option where one can paste any table which has year in column one and earnings in column 2? Maybe even for both past and future years?

**Comment by Gregable** [comment]
Fixed.
