### ISSUE TITLE
Officially, the actual credit for delayed benefits is not immediately applied in all cases

### ISSUE THREAD

**Issue by stkeros** [Gregable/social-security-tools#56]
E.g suppose a July 2nd birthday  and a FRA of 67. One files in June of age 68 to start benefit in July. The initial benefit at age 68 will only receive 6 months of delayed credits (for July to December of the previous year). Because delayed credits are calculated based on the number of months earned in the previous calendar year. Then in January of the year the person turns 69, he/she will get credit for the addition delay earned (Jan to June of age "68"). 

There is one exception: If one waits until age 70, one gets all the credits due to them immediately.

So what the calculator is calculating is not that actual benefit as of a given age/date, but rather the expected future "long term" benefit.

**Comment by Gregable** [comment]
This is something I was unaware of. Can you clarify if I understand correctly given the following extra details:

Lets say this person has a PIA of $1,000. So, they should receive an 8% per year increase in delayed credits in the simple model. Let's also assume that the COLA adjustments are all 0 for simplicity.

Are you saying that:
 - The benefit check in July would be for $1,040.
 - The benefit check in January and onwards would be for $1,080.

**Comment by stkeros** [comment]
Yes, your understanding is correct.

E.g. My personal PIA is 1318. If I file at age 68 to receive benefits for my April birthday, my PIA gets NINE months of increment (6%) and the benefit is $1397 from April until Dec. But then in January my delayed credit "amount" now increases to 8%, and my benefit rises to $1424.

**Comment by stkeros** [comment]
Another corner case which might be addressed in an assumptions/disclaimers section?

It's going to be hard and/or out of scope to represent the benefit on a month by month basis, graphically, and/or a lot of time/text would be devoted to explaining what's going on. You could consider a link to an example from the assumptions page, either an explanation someone else made, or one you provide. But "this calculator assumes you earn the delayed benefit credits immediately, so that your actual benefits might be slightly lower, but only from the month you first receive benefits to the following January".

**Comment by Gregable** [comment]
Does this have any effect on early benefits, or only delayed benefit credits? 

For a person with an July 1 birthday (to keep it simple) who first starts benefits at an NRA of exactly 67, would they be getting a reduction for being considered only 66 and 6 months earned in the previous year?

I think [this](https://secure.ssa.gov/apps10/poms.nsf/links/0300615690), section **B** is the relevant part, and it only refers to delayed retirement credits, but it also doesn't explicitly mention that it does not apply to early reductions.

**Comment by stkeros** [comment]
Only applies to DRC. Reduced credits are immediate. At least, I have never heard anything to the contrary. 

Also, something I may have pointed out long ago, reduced benefits (and some other calcs) are made with fractions, not decimals:

> EXAMPLE: A PIA of $802.80 is to be reduced for 5 months. The applicable calculation is $802.80 x 175/180. First multiply $802.80 by 175 and then divide by 180 for an MBA of $780.50.
> 
> Failure to follow this order can result in the same error as that caused by using the decimal equivalent. If you divide 175 by 180 and then multiply by $802.80, the result is $780.49. After rounding, the MBA would be $780.40.

**Comment by stkeros** [comment]
I'm not sure I can see any difference in any of the outputs? Do you mean that the benefit (spouse or self or both?) is shown somehow as X at filing age then X + Y*DRC, then later as X + DRC the next January? Where Y is the fraction of delayed credits earned in the previous calendar year?

**Comment by Gregable** [comment]
![4zxn4qwhvbk](https://user-images.githubusercontent.com/25519/42105303-afabc89c-7b84-11e8-841f-a102c55bde45.png)

Here's the chart using the first demo data link. Only changes are that I adjusted the spouse PIA to $1,000 and moved both sliders to the right of NRA. You can see the little 'notches' that show reduced DRC until the first full year after filing date.

None of the other data is different, only this one chart.

**Comment by stkeros** [comment]
I don't see what you are seeing? Oh wait, hard refresh!! Now I see it. I wasn't seeing the update. Sorry.

**Comment by stkeros** [comment]
> Also, I'm not sure I'm happy with the position of the $ labels on the chart in these cases, so I may revisit that a bit.

Move the "final" benefit to the right, so that it's after the notch, e.g. left-justified with the notch. But then how about a number with an arrow to the left of the initial benefit. E.g. "$1000 -->" which points to the initial benefit? I have no idea how difficult that is to code to it may be a silly suggestion.

**Comment by Gregable** [comment]
Drawing on this is straightforward. The hard (fun) part is figuring out all of the corner cases of where arrows should be so that they don't stack on each other / get cut off / etc.

For example, consider this corner case:

![socialsecurity tools_beta_app html](https://user-images.githubusercontent.com/25519/42106807-239eaa08-7b8a-11e8-8658-8f3478e7eb3a.png)

The spouse now earns 3 different amounts at different times. The first 2 amounts are based on spouse's own benefit only, the first is with only partial DRC and the 2nd with full DRC. The third amount is the spousal benefit based on half of Self's PIA.

**Comment by Gregable** [comment]
Let me know what you think of the state of this fix now. There are some text boxes labelled "Special Rule" added, one of which (attempts to) explain the delay in applying delayed credits. This box is under the "Early and Delayed Retirement" header.

> Delayed "credits" are calculated based on the number of months earned in the previous calendar year, unless you wait until age 70.
> 
> If you begin delayed benefits in the middle of the year, you will have a few percent smaller benefit than the full delayed benefit. This difference will go away beginning January of the following year.

The dollar labels also track much better. For each label, the algorithm first tries to write the label to the top/bottom of the labelled region. It will shorten the text label if needed, so "$842 / mo" will shorten to "$842". If that's still not enough space, it will attempt to place the label to the left of the labelled region as the next fallback, again trying first the longer text then the shorter. No two labels are allowed to overlap on either vertical or horizontal bands, as that could cause some confusion.

**Comment by stkeros** [comment]
I like it, except, when moving the slider, the dollar benefit label can "jump" around which is distracting. What about always putting a benefit to the right, in the middle of the bar. And then only having one on top/below in cases where there is more than one value.

E.g., in the image below, why not put the $1023 value in the same location as the $548 for the spouse, i.e. in the "middle left" of the bar?

This might be a partial solution to the photo you posted earlier, of a corner case with 3 values for spouse

![image](https://user-images.githubusercontent.com/25359648/42130638-af456da6-7cb8-11e8-9558-5ebec0a6e161.png)

**Comment by Gregable** [comment]
The problem I have with left labels is that it's less clear what it's labeling.  Consider this case:

![screenshot from 2018-06-30 20-28-58](https://user-images.githubusercontent.com/25519/42130813-6788240e-7ca4-11e8-92bc-e77131096516.png)

If $760 / mo were displayed to the left, the user might reasonably be confused as to if that's in addition to the $337/mo or is a totalled value. By being adjacent to the short vertical line, it seems to be labelling that line's height.

Placing the label below the box makes it clearer that it's a total, by being adjacent to the horizontal line indicating a y-value.

It's less of an issue with the leftmost label, such as the example you show. However, it seems better to be more consistent in the labeling, if possible, leading to preferring the same choices for all labels, rather than choosing left for the leftmost label and below/above for the others.

**Comment by stkeros** [comment]
Ok fair, that $1646 to $1656 transition is a little awkward/weird looking. Not sure I have a great solution, other than to say those cases will be relatively rare?

Wait, totally unrelated, I'm just now noticing the bitmoji icon to the right of "preview". Has it always been there? Don't answer. It's totally distracting and uncessessary for our discussion (and kinda weird for github in general, no?). But I have to do it just once. Please excuse my lack of maturity. There is no good social security bitmoji so I will just leave you with the one below. 

 ![bitmoji](https://render.bitstrips.com/v2/cpanel/88e9bc51-35da-49e1-a9b6-e76f28575f3f-6ebe38a4-1789-43f8-9878-8b56face7d70-v1.png?transparent=1&palette=1&width=246)

**Comment by Gregable** [comment]
I have no idea what you are talking about, maybe this is something only you can see on github?

Anyway, I think I'll close this one. :)
