### ISSUE TITLE
If the "spouse" has the higher PIA, the calculator is currently changing the spousal benefit based on retirement age of spouse (not correct).

### ISSUE THREAD

**Issue by stkeros** [Gregable/social-security-tools#59]
I used the 1985 demo, no earnings. I'm "A", spouse is "B". I assigned a PIA of $5000 to B, born in 1990.

When "A"s slider is adjusted, the spousal benefit which starts at "B"s retirement age also changes. I don't think this is right. The spousal benefit would not depend on when spouse files.

That is, I'm not sure that if spouse delays their OWN filing, that that will affect the benefit they may receive in the future as a spouse. But as I'm tying these words, I'm not positive of that.

Eg, in the image below, moving the slider to the left increases both the personal benefit and the spousal benefit?

Also, currently, changing the age of "B" does not change "A"s benefit. But I think "A"s spousal benefit would increase for years 62-67 for B (but no extra spousal benefit for delaying past 67).

I hope that isn't too confusing.

![capture](https://user-images.githubusercontent.com/25359648/41669331-8c0a284a-747f-11e8-8447-da2523ca7d15.PNG)

**Comment by stkeros** [comment]
I think you are correct overall and I am likely wrong on the second part as you note: https://www.ssa.gov/planners/retire/applying6.html 

Let me see if I can think through this. Let's assume a female spouse with a male husband.

"If you begin receiving benefits between age 62 and your full retirement age, the amount will be permanently reduced by a percentage based on the number of months up to your full retirement age."

This tells me that her spouse's benefit is reduced if filing prior to full retirement age. Which benefit? I assume only the spousal benefit. Because we know if she works past full retirement age any benefit based on her own record will get delayed retirement credits.

"If you begin receiving benefits at your full retirement age, your benefit as a spouse cannot exceed one-half of your spouse's full retirement amount."

This emphasizes no delayed credits on the spousal part. AND it specifically notes that the max spousal benefit is half of the "full retirement amount". But I'm confused if that refers to the PIA at age 67 (or whatever) or the full benefit including any delayed credits? I think now that it's referring to the benefit at full retirement age (e.g. a fixed amount). And thus the spousal benefit is independent of when the husband files.

So looking at the example in the graphic, A's slider aka filing age affects her own benefit. HER portion of the benefit increases all along age 62-70. B's slider aka filing age will not affect the spousal benefit of A, because his filing age does not influence his spouse's benefit. But A's age DOES affect the spousal benefit from age 62 to FRA (it's reduced see here: https://www.ssa.gov/OACT/quickcalc/spouse.html#calculator). But after FRA she gets no credits to the spousal benefit.

Summary: 
-- the husband's filing date only affects when the wife can begin claiming a spousal benefit
-- The wife's filing data affects her benefit throughout age 62 to 70
-- The wife's spousal benefit from FRA to age 70 is simply one half the husband's benefit at FRA
-- The wife's (current of future) spousal benefit is reduced if she files from age 62 to FRA (see the annoying formula below).

It was confusing to me that if a wife files early, before qualifying for a spousal benefit, it will affect her future wife's benefit, but that seems to be the case. Note that I turn myself around each time I think about this, so I'm not guaranteeing the accuracy of my comments!

STK

Spousal Reduction formula: "A spousal benefit is reduced 25/36 of one percent for each month before normal retirement age, up to 36 months. If the number of months exceeds 36, then the benefit is further reduced 5/12 of one percent per month."

**Comment by Gregable** [comment]
Actually, my interpretation of the laws was slightly different. 

The way I understood this to work is that you first make all calculations based entirely on PIA, so filing dates and ages don't enter at this stage. 

For example: husband has $1,000 PIA and wife has $100 PIA. 
You calculate wife's personal benefit as wife's PIA, so $100 and wife's spousal benefit as half of husband's benefit minus the wife's personal benefit, so $400.

Personal: $100
Spousal: $400

Now, filing dates enter the picture, and the husband's PIA is no longer part of the remaining calculation. 

Both the $100 and $400 values are adjusted based on the difference in date for the wife's filing of each of these components of her benefit. Personal is adjusted just like the normal early/delayed credits for PIA, so it increases all the way from filing at 62 - 70. Spousal is adjusted only for years before the FRA of the wife (67 or whatever). 

The filing date/age for personal and spousal of the wife might be the same, if for example the wife files at a date later than the husband, or may be different if the wife files before the husband.

This can lead to a situation where wife receives both the full $400 spousal benefit and a reduced personal benefit. This would be the case where the wife files before her own FRA, but the husband files after the wife's FRA. In this case, the total benefit might be $480 or something ($400 spousal and $80 personal).

The confusion comes in where most people think of the spousal benefit as 1/2 of the husband personal benefit. This is not the spousal benefit, it's the total benefit. The spousal benefit is that minus the personal benefit. This leads people to think that the spousal benefit just means the higher of personal or 1/2 spousal, but that's only correct in the specific case where the wife files for both benefits at FRA.

Anyway, I hope my explanation of my understanding is clear. What I'm far less sure about is whether or not I'm _correct_.

**Comment by stkeros** [comment]
> This can lead to a situation where wife receives both the full $400 spousal benefit and a reduced personal benefit. This would be the case where the wife files before her own FRA but the husband files after the wife's FRA. In this case, the total benefit might be $480 or something ($400 spousal and $80 personal).

In this example, if the wife files before FRA, it means husband has not yet filed. So wife can only take a personal benefit, and it is reduced as if she were single. Later the husband files. She is eligible for a spouses benefit. My questions are, 1) MUST she take the spousal benefit when eligible and 2) is her reduction, if any, based on the age she originally filed for her personal benefit or is it when she began to receive her spouses benefit?  I don't think I actually know the answers to those questions right now.

> The confusion comes in where most people think of the spousal benefit as 1/2 of the husband personal benefit. This is not the spousal benefit, it's the total benefit. The spousal benefit is that minus the personal benefit. This leads people to think that the spousal benefit just means the higher of personal or 1/2 spousal, but that's only correct in the specific case where the wife files for both benefits at FRA.

This I understand, and you are correct. But in your example in this thread of the husband with the $1000 PIA. The max spousal benefit is $500. If wife had no earnings, she would receive $500 at FRA. So I don't see why a wife with a PIA of $100 who filed early ($80) would only get $480, rather than being "topped off" to the full spousal amount. You may be correct, but this is another point I do not know. 

I am going to see if I can find definitive answers to these questions. :)

**Comment by stkeros** [comment]
I think the example on this page answers all of our questions (see case 2):
https://www.bogleheads.org/wiki/Social_Security

And ultimately I think your understanding is correct!

**Comment by stkeros** [comment]
> Ah, OK. I think you are correct on the first part. What the calculator is doing is calculating the starting date of the spousal benefits to be the earlier of the A or B's filing date, but it needs to be the later of A or B's filing date.

Ok, circling back to the beginning, I understand your  comment better. What the calculator is currently doing, if an older lower earning wife files for her own benefit before FRA, is reducing the spousal benefit AS IF she were to receive it as of that date (even if husband doesn't file until after wife's FRA, which officially begins the spousal benefit).

I think perhaps fix this calculation and we can move onto trying to find other errors! (if any).

**Comment by Gregable** [comment]
Yes. I pushed a fix just now. Make sure you hard-refresh in your browser to pick it up.

**Comment by stkeros** [comment]
works
