### ISSUE TITLE
Calculator allows for benefit at age 61, which is not allowed until 62+one month

### ISSUE THREAD

**Issue by stkeros** [Gregable/social-security-tools#60]
The earliest one can file is age 62, and the first benefit will be received to pay for the month the worker is 62 and one month old. So the left-most position on the slider is one month to early.

**Comment by Gregable** [comment]
Assume 67 NRA. If one files at age 62 and begins at 62+1m, does that end up with a reduced benefit based on 5 years early benefit or 4 years 11 months?

**Comment by Gregable** [comment]
https://www.ssa.gov/planners/retire/applying3.html

> The earliest age at which you can begin receiving your Social Security retirement benefits is 62. You can apply for your benefits 3 months before you turn 62 if you want your payments to start at that age.

I think this is fine then, but may need to tighten the language up slightly to make it clear that the slider is selecting the benefit start date, not the filing date. Does this sound reasonable?

**Comment by stkeros** [comment]
So I left out some detail when talking about the 62 vs 62+one month issue.

One can only collect benefits for that month if one is 62 for the WHOLE month. This only applies if your birthday is the first or second of the month (because you have 'reached' 62 the day before). So an April 2 birthday can get a check for the first month of turning 62 (I think check will be received in May), and the payout level is 70%.

If you have an April 1 birthday, the first month you are eligible to collect a benefit is still April of course, but SS considers you to have turned 62 on March 31st. So you get reduction based on 62+ one month or 70.4% of full benefit.

So only those born on the first or second of the month can actually receive a benefit for the month they turn 62. Maybe this is too much detail for such a calculator which after all is just an estimate. And even as an educational tool, that kind of details is getting into the weeds? Maybe leave it as is. 

I agree that if you change the wording to be "benefit start date" then it's accurate. Only a subset of people can actually receive a benefit for the first month they turn 62. But then, the reductions are different depending on whether it's a first or second of the month birthday. Now you know why my spreadsheet has a disclaimer that it's "accurate for Jan 2nd birthdays" and it ignores several edge effects. :)

**Comment by stkeros** [comment]
What about a disclaimer/assumptions section to describe some of the corner issues. 

E.g. "actual benefits and start dates will vary from these numbers if your actual birthday falls on the first or second of the month" perhaps with a link to an explanation?  https://secure.ssa.gov/poms.nsf/lnx/0300615015

**Comment by Gregable** [comment]
I think this is now essentially a duplicate of https://github.com/Gregable/social-security-tools/issues/57 - let me know if I'm missing anything.

**Comment by Gregable** [comment]
I think this is out of date and has been resolved.
