### ISSUE TITLE
What's the "name" of the site?

### ISSUE THREAD

**Issue by stkeros** [Gregable/social-security-tools#67]
When I tell people to go to the site, what am I telling them to go to?

Go to "Social Security Tools?" "Understand Social Security?"

**Comment by Gregable** [comment]
I refer to it as "social security tools" given the URL, but open to other ideas. The root page could be improved or maybe even gotten rid of.

**Comment by stkeros** [comment]
Social Security Tools works for me. The plural can refer to the various features of the calculator (PIA calc, filing date visualizer, etc).

Here is one example of how it looks _in situ_ . https://www.doctoredmoney.org/ss-benefit-calculator  (6th paragraph)

**Comment by Gregable** [comment]
Yeah, I probably would have gone for .tool but there is no such top-level-domain.

I was watching the recent .app domain drop to see if I could get ssa.app which would have been sweet, but alas someone bought it at an early stage of the auction that indicates they paid a few thousand dollars for it.

**Comment by Gregable** [comment]
Hm, I hadn't looked for a while, but ssa.tools is available. I just bought it. Seems a little easier to type in / remember, may make that change at some point.
