### ISSUE TITLE
Actual age on slider obscures fixed age text on page.

### ISSUE THREAD

**Issue by stkeros** [Gregable/social-security-tools#69]
This is cosmetic, but the label for the actual age for which the slider is set overlaps the 62...70 when not set on an integer setting, and is hard to read.

Consider
1) Deleting the fixed labels once the slider is moved. It will be clear that the range is 62 to 70
2) Only label 62, and 70, either as is, or to the left and right of the slider, while preserving the text for the slider setting just about the movable dot.

On a related note (new issue?) the lines upon which the slider moves extends just a bit to the left and right of 62/70. I assume this is how the stock code for that graphic behaves. Consider truncating the line so that it doesn't extend past the end of the dots. Minor issue. One can play with such things forever.

**Comment by Gregable** [comment]
The little overhanging lines represent the radius of the slider wheel. It didn't occur to me that they might cause the user to think that the range of available dates is before or after 62 / 70 respectively, but that makes sense. I'll remove them.

**Comment by stkeros** [comment]
> The label sets a background block that will cover any text behind it, but with a 30% transparency. I didn't want to completely hide the age labels, as it helps orient the user ("I turn 68 in the middle of year 2033").
> 
> I can make the label background block wider, or less transparent, even opaque white for example.

I do think, maybe, that 100% opacity of the slider label might be better? The situations as show below just look unreadable to me. Just a subjective opinion of course.

![image](https://user-images.githubusercontent.com/25359648/42130668-58445930-7cb9-11e8-93c8-145ea9695584.png)

![image](https://user-images.githubusercontent.com/25359648/42130670-733b1ec2-7cb9-11e8-9845-69bd8bb3454b.png)

**Comment by Gregable** [comment]
Made the slider labels fully opaque and widened their padding a bit.
