### ISSUE TITLE
Left and right vertical lines on the graph look awkward.

### ISSUE THREAD

**Issue by stkeros** [Gregable/social-security-tools#70]
What about getting rid of the y-axis on the left entirely. Then on the right, change it so that it more clearly represents this is the benefit which will persist. I've mocked up a kind of line break and ellipses, but it can be anything. Deciding on an right-y-axis feature may be a precursor to a future revision which attempts to show widow benefits upon death. 

![image](https://user-images.githubusercontent.com/25359648/41972824-086f4616-79e1-11e8-8322-d2f52947f95c.png)

**Comment by Gregable** [comment]
Dropping the left axis makes sense. Not sure about the right, I think there is a risk that users would interpret symbols or indicators there incorrectly. Then again, your point is that users may interpret the current benefits as ending at the right hand side.

One other thought I had was maybe having the right hand side edges have a gradient where each box fades from it's current color to white over 50-100 pixels, without having a defined right edge.

**Comment by stkeros** [comment]
> One other thought I had was maybe having the right hand side edges have a gradient where each box fades from it's current color to white over 50-100 pixels, without having a defined right edge.

I like that idea, no hard edge just a fade into uncertainty, ha hah

**Comment by Gregable** [comment]
I've removed the left and right axes. The bottom axes started looking weird at that point, so I removed it to.

The gradient is a little more tricky, but I think the fact that the right hand border is missing is indicative.
