### ISSUE TITLE
Describe to the user how survivor benefits work

### ISSUE THREAD

**Issue by Gregable** [Gregable/social-security-tools#71]
From @MikePiper:

> Try to make sure the reader/user is considering survivor benefits as well.
> 
> As one really simple example, imagine two people, each with a PIA of $1,000 and FRA of 67. And they're considering Strategy A in which one files at 62 and the other at 70, as opposed to Strategy B in which both spouses file at their FRA.
> 
> Strategy A gives them monthly income of: $700 + $1,240 = $1,940
> Strategy B gives them monthly income of: $1,000 + $1,000 = $2,000
> 
> Based only on these two amounts, it looks like the second strategy might be slightly preferable. But once we think about survivor benefits, we see that the first strategy has a considerable advantage in that regard (because after one dies, the survivor is left with a monthly benefit of $1,240 instead of $1,000).

**Comment by stkeros** [comment]
This goes back to a suggestion to have the user input death dates, or have default death dates with sliders or something like that. So that benefits are payable until death, but then one of the benefits persists after death of one of the spouses. This really changes/complicates the graphic though.

**Comment by Gregable** [comment]
I don't think this would really fit well into the current chart. More of a thought about additional text / chart below the spousal date selection.

**Comment by Gregable** [comment]
I added a section on survivor benefits. Just some light text so far.

I also expanded the FAQ bit on "what age should I file" to a full-on section. It's a bit text heavy, which I worry. The other sections all tell you specific calculations that are happening and this one has fuzzy vague recommendations like "if you are unhealthy, you may want to file early". At the end, I point users to Mike's OpenSocialSecurity.com, since imho that's the best thing out there today.

I do think I want to eventually add some more calculations around selecting optimal dates, but that's a long way off.
