### ISSUE TITLE
Consider having the sliders even in the not-married case

### ISSUE THREAD

**Issue by stkeros** [Gregable/social-security-tools#74]
If the user selects not married, there are no sliders. However as simple as the output/graphic might be, the slider is an interactive element that illustrates the early and delayed benefits nicely, even if a chart/table is sufficient. Especially now that you've illustrated the effect of delayed credits which are not fully applied at first.

**Comment by stkeros** [comment]
> Do you feel like it adds much value beyond the line chart in the "Early and Delayed Retirement" section?

No. I don't feel strongly about it. But I don't think it detracts at all and allows for visualizing the delay in the delayed credit payments. Minor thing either way.

**Comment by Gregable** [comment]
There are now slider-charts for each individual after the last redesign.
