### ISSUE TITLE
The root page for the site is horrible

### ISSUE THREAD

**Issue by Gregable** [Gregable/social-security-tools#80]
I'm referring to the piggy bank image page at https://socialsecurity.tools/. It's completely useless, and does very little to help the user determine if this tool is worth their effort to login to ssa.gov, copy/paste their earnings report, etc.

I'm not really sure what should be on this page, but the piggy bank and "Understand Social Security" are not the right answer.

**Comment by Gregable** [comment]
Note for inspiration. In terms of images, flipping around google images turned up https://i2.cdn.turner.com/money/dam/assets/150611105148-social-security-retirement-780x439.jpg. I can't use this image, but it could be useful for inspiration.

**Comment by stkeros** [comment]
Also, it's hard to get "back" to the root page, in that the "home" button at the top right doesn't do anything depending on the page one is on. this is probably only relevant if one want to go through the demo scenarios.
