### ISSUE TITLE
Rearrange the report flow

### ISSUE THREAD

**Issue by Gregable** [Gregable/social-security-tools#83]
Currently, the report requests the earnings report from a single user, then their birthdate. It then displays a bunch of single-user data followed by a request for spousal data. This was done by organically moving from a single-user display to a spousal display.

I propose a different flow. Initially the user just clocks a big "BEGIN" button. A document is displayed which has three headers:

- Birthday
- Earnings Data
- Are you married

These are all just data-entry headers. Once birthday AND earnings data are entered, new sections appear below with PIA calculations, Normal Retirement Age, and Early / Delayed retirement table as today. The Early / Delayed retirement chart is removed completely.

If the married Selector is chosen, similar data inputs appear for Spouse, and as those are filled in, new sections appear for the spouse, essentially forming two reports. The spousal report would discuss spousal benefits or personal benefits, or both, depending on the situation from the data entry.

Below both of those two sections, we would display the "Early and Delayed Combined Retirement" section which replaces the Early / Delayed retirement chart. It needs to be updated to potentially show only one user, if that person is not married, but would use a slider.

**Comment by stkeros** [comment]
Ah, I hadn't seen this issue when I suggested "tabs" for entering self/spouse data in another issue. But this is essentially what I had in mind. I think your proposal here is good. Acquire the data in advance, report later. I don't care for the request for "are you married" at the end of the "self" report. Also allows for the possibility to take earnings after 62 into account for each, if desired, now or as a future feature.

**Comment by Gregable** [comment]
While the implementation was a little different, I'm going to consider this one complete after the redesign.
