### ISSUE TITLE
About page: Have a date in accuracy section

### ISSUE THREAD

**Issue by stefanbeller** [Gregable/social-security-tools#93]
While the accuracy section in the about page is all about voiding any warranty and stating that you shall do your own research, people may choose to trust the tools provided nevertheless.

And to estimate how much to trust the formulas/data presented, it would be good to have a phrase as "This is believed to be accurate as of Sept 2018 [but does not include the upcoming senate bill XYZ]" or so.

Not sure if such a phrase can be automated in any way. :/

**Comment by Gregable** [comment]
Thus far, I'm committing to keeping this up to date. If the law changes, I'll add a warning at that time.

**Comment by Gregable** [comment]
Added a string to the about page that I'll try to update regularly.
https://ssa.tools/about.html

> The site was most recently updated on Dec 24, 2019. This update included the latest computed values from the Social Security Administration.
